### ISSUE TITLE
[Tracking Issue] Table Usability Improvements

### ISSUE THREAD

**Issue by theangchen** [NMFS-RADFish/boilerplate#169]
**Technical Specifications**
- [x] NMFS-RADFish/boilerplate#168

**Issues**
- [ ] NMFS-RADFish/boilerplate#168  
- [x] NMFS-RADFish/boilerplate#170 
- [x] NMFS-RADFish/documentation#44 

**Working branches**
- [x] [Data and sorting](https://github.com/NMFS-RADFish/boilerplate/tree/169-table-data-sort-improvements)
- [x] [Pagination](https://github.com/NMFS-RADFish/boilerplate/tree/169-table-pagination-improvements)

**Comment by theangchen** [comment]
- Isaiah will be working on props, pagination
- Jay will be working on table rows, toggle show/hide, sorting

**Comment by theangchen** [comment]
This was released with [0.16.0](https://github.com/NMFS-RADFish/boilerplate/releases/tag/0.16.0)
